<?php
// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Mp3Player
{
    global $Mp3Player__t_Player;
    global $Mp3Player__t_PlayerPrx;

    class PlayerPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Mp3Player::Player', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Mp3Player::Player', $facet);
        }

        public static function ice_staticId()
        {
            return '::Mp3Player::Player';
        }
    }

    $Mp3Player__t_Player = IcePHP_defineClass('::Mp3Player::Player', '\\Mp3Player\\Player', -1, false, true, $Ice__t_Value, null);

    $Mp3Player__t_PlayerPrx = IcePHP_defineProxy('::Mp3Player::Player', $Ice__t_ObjectPrx, null);

    IcePHP_defineOperation($Mp3Player__t_PlayerPrx, 'addNewFile', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string)), null, array($IcePHP__t_string), null);
    IcePHP_defineOperation($Mp3Player__t_PlayerPrx, 'findByFeature', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string)), null, array($IcePHP__t_string), null);
    IcePHP_defineOperation($Mp3Player__t_PlayerPrx, 'deleteFile', 0, 0, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_string), null);
}
?>
